package main

import (
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// The fixture exercises the declaration shapes the format has to be stable
// about: implicit const repetition, a var with no declared type, struct tags,
// embedded and unexported members, an alias, an interface, and a generic type
// with a method.
const fixture = `package demo

import "context"

const (
	KindA Kind = iota
	KindB
	kindHidden
)

const Public = "p"

var (
	// ErrBoom is a sentinel.
	ErrBoom = errors.New("boom")
	Limit   int = 5
	hidden      = 1
)

// Kind names a thing.
type Kind string

type Alias = context.Context

type Option func(*Set[int])

type Set[T any] struct {
	Items []T ` + "`json:\"items\"`" + `
	Kind
	seen map[string]bool
}

func (s *Set[T]) Add(v T) bool { return false }

func (s *Set[T]) drop() {}

type Reader interface {
	Read(p []byte) (n int, err error)
	private()
}

type Empty struct{}

func New(ctx context.Context, opts ...Option) (*Set[int], error) { return nil, nil }

func helper() {}
`

const subFixture = `package sub

// Only the exported half is listed.
func Exported() {}

func unexported() {}
`

const want = `# Exported API of example.com/m/pkg and its public subpackages.
#
# Generated by ` + "`make api`" + `; do not edit by hand. ` + "`make api-check`" + ` fails when
# this file no longer matches the source, so a public API change lands as a
# diff here. A line that changes or disappears is usually a breaking change,
# and so are three kinds of added line: a method added to an exported
# interface; a constant inserted into an iota block, which renumbers the ones
# after it; and a slice, map or func field added to a struct that was
# comparable, which stops every == on it from compiling — and which leaves no
# diff here at all when the field is unexported and the struct already had
# unexported fields. ` + "`make api-compat`" + ` classifies the delta.

package demo // example.com/m/pkg

const KindA Kind = iota
const KindB Kind
const Public = "p"

var ErrBoom = errors.New("boom")
var Limit int = 5

func New(ctx context.Context, opts ...Option) (*Set[int], error)

type Alias = context.Context

type Empty struct{}

type Kind string

type Option func(*Set[int])

type Reader interface {
	Read(p []byte) (n int, err error)
	// unexported methods
}

type Set[T any] struct {
	Items []T ` + "`json:\"items\"`" + `
	Kind
	// unexported fields
}
func (*Set[T]) Add(v T) bool

package sub // example.com/m/pkg/sub

func Exported()
`

func TestRun(t *testing.T) {
	root := t.TempDir()
	write(t, filepath.Join(root, "go.mod"), "module example.com/m\n\ngo 1.25.0\n")
	write(t, filepath.Join(root, "pkg", "demo.go"), fixture)
	write(t, filepath.Join(root, "pkg", "demo_test.go"), "package demo\n\nfunc TestNotListed(t *testing.T) {}\n")
	write(t, filepath.Join(root, "pkg", "sub", "sub.go"), subFixture)
	write(t, filepath.Join(root, "pkg", "internal", "secret", "secret.go"), "package secret\n\nfunc Hidden() {}\n")
	write(t, filepath.Join(root, "pkg", "testdata", "data.go"), "package data\n\nfunc Fixture() {}\n")

	var out strings.Builder
	if err := run(&out, filepath.Join(root, "pkg")); err != nil {
		t.Fatalf("run: %v", err)
	}
	if got := out.String(); got != want {
		t.Errorf("surface mismatch\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// The fixture spreads methods over several types and over two files, in an
// order that is neither the declaration order nor the sorted one, because
// methods are collected into a map keyed by receiver and appended in the order
// the files are parsed. That collection is the one place the output could pick
// up an ordering that isn't the source's, so a determinism test that lists no
// methods proves nothing.
const orderFixtureA = `package demo

func A() {}

func (a Alpha) Three() {}

func (b *Beta) Zed() {}

type Gamma struct{}

func (g Gamma) Mid() {}
`

const orderFixtureB = `package demo

type Alpha struct{ N int }

func (a Alpha) Two() {}

func (a *Alpha) One() {}

type Beta struct{}

func (b *Beta) Ant() {}

func (g Gamma) Begin() {}
`

// The listing is a gate, so it has to be the same bytes on every run and on
// every machine: the walk, the method collection, the sorts and the printer
// all have to be independent of file-system order, and the output may not
// carry any trace of where the tree happens to live.
func TestRunIsDeterministic(t *testing.T) {
	files := map[string]string{
		"go.mod":            "module example.com/m\n",
		"pkg/b.go":          orderFixtureB,
		"pkg/a.go":          orderFixtureA,
		"pkg/sub/sub.go":    "package sub\n\ntype S struct{}\n\nfunc (s S) B() {}\n\nfunc (s S) A() {}\n",
		"pkg/a_test.go":     "package demo\n\nfunc (a Alpha) NotListed() {}\n",
		"pkg/sub/extra.go":  "package sub\n\nfunc (s S) C() {}\n",
		"pkg/sub/aextra.go": "package sub\n\nfunc (s S) D() {}\n",
	}

	root := t.TempDir()
	for name, content := range files {
		write(t, filepath.Join(root, filepath.FromSlash(name)), content)
	}

	var first strings.Builder
	if err := run(&first, filepath.Join(root, "pkg")); err != nil {
		t.Fatalf("run: %v", err)
	}
	// Guard against the fixture rotting into one with no methods in it, which
	// is how this test passed by construction once already.
	if n := strings.Count(first.String(), "\nfunc ("); n < 8 {
		t.Fatalf("fixture lists %d methods, too few to exercise the ordering:\n%s", n, first.String())
	}
	// Alpha's three methods are declared across both files, in neither
	// declaration nor sorted order, so this run is only stable because the
	// methods of a type are sorted after collection.
	if run := "func (*Alpha) One()\nfunc (Alpha) Three()\nfunc (Alpha) Two()\n"; !strings.Contains(first.String(), run) {
		t.Errorf("methods are not sorted under their receiver; want a run of\n%s\ngot:\n%s", run, first.String())
	}

	for range 3 {
		var again strings.Builder
		if err := run(&again, filepath.Join(root, "pkg")); err != nil {
			t.Fatalf("run: %v", err)
		}
		if again.String() != first.String() {
			t.Fatalf("two runs over the same tree disagree\n--- first ---\n%s\n--- again ---\n%s",
				first.String(), again.String())
		}
	}

	// The same sources at a different absolute path, written in a different
	// order, have to produce the same bytes. This is the property the old
	// export-data baseline did not have: it embedded the generating machine's
	// directory, so two checkouts could never agree.
	other := t.TempDir()
	names := make([]string, 0, len(files))
	for name := range files {
		names = append(names, name)
	}
	sort.Sort(sort.Reverse(sort.StringSlice(names)))
	for _, name := range names {
		write(t, filepath.Join(other, filepath.FromSlash(name)), files[name])
	}

	var elsewhere strings.Builder
	if err := run(&elsewhere, filepath.Join(other, "pkg")); err != nil {
		t.Fatalf("run: %v", err)
	}
	if elsewhere.String() != first.String() {
		t.Fatalf("the same tree at a different path disagrees\n--- %s ---\n%s\n--- %s ---\n%s",
			root, first.String(), other, elsewhere.String())
	}
}

// Non-test files in one directory disagreeing on their package name is an
// error rather than a coin toss on whichever sorts first.
func TestRunRejectsDisagreeingPackageNames(t *testing.T) {
	root := t.TempDir()
	write(t, filepath.Join(root, "go.mod"), "module example.com/m\n")
	write(t, filepath.Join(root, "pkg", "gen.go"),
		"package main\n\nfunc Generate() {}\n")
	write(t, filepath.Join(root, "pkg", "real.go"), "package demo\n\nfunc Real() {}\n")

	var out strings.Builder
	err := run(&out, filepath.Join(root, "pkg"))
	if err == nil {
		t.Fatalf("want an error for files disagreeing on package name, got none:\n%s", out.String())
	}
	if !strings.Contains(err.Error(), "gen.go") || !strings.Contains(err.Error(), "real.go") {
		t.Errorf("the error should name both files, got: %v", err)
	}
	if strings.Contains(out.String(), "func Generate") {
		t.Errorf("the generator's symbols reached the listing:\n%s", out.String())
	}
}

func TestRunRejectsBuildConstraints(t *testing.T) {
	tests := []struct {
		name     string
		file     string
		content  string
		wantFile string
		wantSub  string
	}{
		{
			name:     "go_build_ignore",
			file:     "pkg/gen.go",
			content:  "//go:build ignore\n\npackage demo\n\nfunc Generate() {}\n",
			wantFile: "gen.go",
			wantSub:  "//go:build ignore",
		},
		{
			name:     "go_build_linux",
			file:     "pkg/linux_tag.go",
			content:  "//go:build linux\n\npackage demo\n\nfunc Linux() {}\n",
			wantFile: "linux_tag.go",
			wantSub:  "//go:build linux",
		},
		{
			name:     "plus_build_legacy",
			file:     "pkg/legacy.go",
			content:  "// +build linux\n\npackage demo\n\nfunc Legacy() {}\n",
			wantFile: "legacy.go",
			wantSub:  "// +build linux",
		},
		{
			name:     "goos_suffix",
			file:     "pkg/file_linux.go",
			content:  "package demo\n\nfunc Linux() {}\n",
			wantFile: "file_linux.go",
			wantSub:  `GOOS suffix "linux"`,
		},
		{
			name:     "goarch_suffix",
			file:     "pkg/file_amd64.go",
			content:  "package demo\n\nfunc Amd64() {}\n",
			wantFile: "file_amd64.go",
			wantSub:  `GOARCH suffix "amd64"`,
		},
		{
			name:     "goos_goarch_suffix",
			file:     "pkg/file_linux_amd64.go",
			content:  "package demo\n\nfunc LinuxAmd64() {}\n",
			wantFile: "file_linux_amd64.go",
			wantSub:  `GOOS/GOARCH suffix "linux_amd64"`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			root := t.TempDir()
			write(t, filepath.Join(root, "go.mod"), "module example.com/m\n")
			write(t, filepath.Join(root, tt.file), tt.content)

			var out strings.Builder
			err := run(&out, filepath.Join(root, "pkg"))
			if err == nil {
				t.Fatalf("want error for build constraint, got none; output:\n%s", out.String())
			}
			if !strings.Contains(err.Error(), tt.wantFile) {
				t.Errorf("error %q should name file %q", err.Error(), tt.wantFile)
			}
			if !strings.Contains(err.Error(), "build constraints are not supported") {
				t.Errorf("error %q should state build constraints are not supported", err.Error())
			}
			if !strings.Contains(err.Error(), tt.wantSub) {
				t.Errorf("error %q should contain %q", err.Error(), tt.wantSub)
			}
			if strings.Contains(out.String(), "\nfunc ") || strings.Contains(out.String(), "\npackage ") {
				t.Errorf("symbols reached listing despite constraint error:\n%s", out.String())
			}
		})
	}
}

func TestRunPermitsTestBuildConstraints(t *testing.T) {
	root := t.TempDir()
	write(t, filepath.Join(root, "go.mod"), "module example.com/m\n")
	write(t, filepath.Join(root, "pkg", "real.go"), "package demo\n\nfunc Real() {}\n")
	write(t, filepath.Join(root, "pkg", "real_test.go"),
		"//go:build race\n\npackage demo\n\nimport \"testing\"\n\nfunc TestRace(t *testing.T) {}\n")
	write(t, filepath.Join(root, "pkg", "real_linux_test.go"),
		"//go:build linux\n\npackage demo\n\nimport \"testing\"\n\nfunc TestLinux(t *testing.T) {}\n")
	write(t, filepath.Join(root, "pkg", "real_linux_amd64_test.go"),
		"// +build linux,amd64\n\npackage demo\n\nimport \"testing\"\n\nfunc TestLinuxAmd64(t *testing.T) {}\n")

	var out strings.Builder
	if err := run(&out, filepath.Join(root, "pkg")); err != nil {
		t.Fatalf("run failed on package with tagged tests: %v", err)
	}
	if !strings.Contains(out.String(), "func Real()") {
		t.Errorf("expected func Real() in output, got:\n%s", out.String())
	}
	if strings.Contains(out.String(), "Test") {
		t.Errorf("test functions should not appear in output, got:\n%s", out.String())
	}
}

func TestCheckFilenameConstraint(t *testing.T) {
	tests := []struct {
		path string
		want string
	}{
		{"file_linux.go", `GOOS suffix "linux"`},
		{"file_darwin.go", `GOOS suffix "darwin"`},
		{"file_windows.go", `GOOS suffix "windows"`},
		{"file_amd64.go", `GOARCH suffix "amd64"`},
		{"file_arm64.go", `GOARCH suffix "arm64"`},
		{"file_linux_amd64.go", `GOOS/GOARCH suffix "linux_amd64"`},
		{"file_darwin_arm64.go", `GOOS/GOARCH suffix "darwin_arm64"`},
		{"file_test.go", ""},
		{"file_linux_test.go", ""},
		{"file_linux_amd64_test.go", ""},
		{"file.go", ""},
		{"linux.go", ""},
		{"amd64.go", ""},
		{"file_bar.go", ""},
		{"file_linux.txt", ""},
	}

	for _, tt := range tests {
		got := checkFilenameConstraint(tt.path)
		if got != tt.want {
			t.Errorf("checkFilenameConstraint(%q) = %q, want %q", tt.path, got, tt.want)
		}
	}
}

func TestRunRejectsEmptyTree(t *testing.T) {
	root := t.TempDir()
	write(t, filepath.Join(root, "go.mod"), "module example.com/m\n")
	if err := os.MkdirAll(filepath.Join(root, "pkg"), 0o755); err != nil {
		t.Fatal(err)
	}
	var out strings.Builder
	if err := run(&out, filepath.Join(root, "pkg")); err == nil {
		t.Fatal("want an error for a tree with no packages, got none")
	}
}

func write(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}
