package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The fixture exercises the declaration shapes the format has to be stable
// about: implicit const repetition, a var with no declared type, struct tags,
// embedded and unexported members, an alias, an interface, and a generic type
// with a method.
const fixture = `package demo

import "context"

const (
	KindA Kind = iota
	KindB
	kindHidden
)

const Public = "p"

var (
	// ErrBoom is a sentinel.
	ErrBoom = errors.New("boom")
	Limit   int = 5
	hidden      = 1
)

// Kind names a thing.
type Kind string

type Alias = context.Context

type Option func(*Set[int])

type Set[T any] struct {
	Items []T ` + "`json:\"items\"`" + `
	Kind
	seen map[string]bool
}

func (s *Set[T]) Add(v T) bool { return false }

func (s *Set[T]) drop() {}

type Reader interface {
	Read(p []byte) (n int, err error)
	private()
}

type Empty struct{}

func New(ctx context.Context, opts ...Option) (*Set[int], error) { return nil, nil }

func helper() {}
`

const subFixture = `package sub

// Only the exported half is listed.
func Exported() {}

func unexported() {}
`

const want = `# Exported API of example.com/m/pkg and its public subpackages.
#
# Generated by ` + "`make api`" + `; do not edit by hand. ` + "`make api-check`" + ` fails when
# this file no longer matches the source, so a public API change lands as a
# diff here. A line that changes or disappears is a breaking change.

package demo // example.com/m/pkg

const KindA Kind = iota
const KindB Kind
const Public = "p"

var ErrBoom = errors.New("boom")
var Limit int = 5

func New(ctx context.Context, opts ...Option) (*Set[int], error)

type Alias = context.Context

type Empty struct{}

type Kind string

type Option func(*Set[int])

type Reader interface {
	Read(p []byte) (n int, err error)
	// unexported methods
}

type Set[T any] struct {
	Items []T ` + "`json:\"items\"`" + `
	Kind
	// unexported fields
}
func (*Set[T]) Add(v T) bool

package sub // example.com/m/pkg/sub

func Exported()
`

func TestRun(t *testing.T) {
	root := t.TempDir()
	write(t, filepath.Join(root, "go.mod"), "module example.com/m\n\ngo 1.25.0\n")
	write(t, filepath.Join(root, "pkg", "demo.go"), fixture)
	write(t, filepath.Join(root, "pkg", "demo_test.go"), "package demo\n\nfunc TestNotListed(t *testing.T) {}\n")
	write(t, filepath.Join(root, "pkg", "sub", "sub.go"), subFixture)
	write(t, filepath.Join(root, "pkg", "internal", "secret", "secret.go"), "package secret\n\nfunc Hidden() {}\n")
	write(t, filepath.Join(root, "pkg", "testdata", "data.go"), "package data\n\nfunc Fixture() {}\n")

	var out strings.Builder
	if err := run(&out, filepath.Join(root, "pkg")); err != nil {
		t.Fatalf("run: %v", err)
	}
	if got := out.String(); got != want {
		t.Errorf("surface mismatch\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// The listing is a gate, so it has to be the same bytes every run: the walk,
// the sort, and the printer all have to be order-independent of the file
// system.
func TestRunIsDeterministic(t *testing.T) {
	root := t.TempDir()
	write(t, filepath.Join(root, "go.mod"), "module example.com/m\n")
	write(t, filepath.Join(root, "pkg", "b.go"), "package demo\n\nfunc B() {}\n")
	write(t, filepath.Join(root, "pkg", "a.go"), "package demo\n\nfunc A() {}\n")

	var first strings.Builder
	if err := run(&first, filepath.Join(root, "pkg")); err != nil {
		t.Fatalf("run: %v", err)
	}
	for range 3 {
		var again strings.Builder
		if err := run(&again, filepath.Join(root, "pkg")); err != nil {
			t.Fatalf("run: %v", err)
		}
		if again.String() != first.String() {
			t.Fatal("two runs over the same tree disagree")
		}
	}
}

func TestRunRejectsEmptyTree(t *testing.T) {
	root := t.TempDir()
	write(t, filepath.Join(root, "go.mod"), "module example.com/m\n")
	if err := os.MkdirAll(filepath.Join(root, "pkg"), 0o755); err != nil {
		t.Fatal(err)
	}
	var out strings.Builder
	if err := run(&out, filepath.Join(root, "pkg")); err == nil {
		t.Fatal("want an error for a tree with no packages, got none")
	}
}

func write(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}
